<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1m0B0TA\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1m0B0TA/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container1m0B0TA.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container1m0B0TA\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container1m0B0TA\App_KernelDevDebugContainer([
    'container.build_hash' => '1m0B0TA',
    'container.build_id' => '987d5fb7',
    'container.build_time' => 1661180779,
], __DIR__.\DIRECTORY_SEPARATOR.'Container1m0B0TA');
